version: '3.7'

services:
  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: firstlab
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"

  webapp:
    container_name: webapp
    build: .
    ports:
      - "8085:8085"
    expose:
      - "8085"
    depends_on: 
      - database
